console.group("Group");
console.log("inside");
console.group();
console.log("deeper");
console.groupEnd();
console.groupEnd();
console.log("outside");
console.count();
console.count();
console.count("x");
console.countReset();
console.count();
console.table([{ a: 1, b: "x" }, { a: 2, c: true }]);
console.table(["p", "q"]);
console.table([{ a: 1, b: 2 }], ["b"]);
console.dir({ d: [1, { e: 2 }] });
console.info("info"); console.debug("debug");
console.assert(true, "not printed");
console.error("to stderr");
console.warn("warn to stderr");
console.assert(1 === 2, "math is broken");
