// Build-time tool: compiles src/js/*.js to QuickJS bytecode and writes them as
// C++ arrays (embedded_js.cpp), so rtn doesn't parse ~4,000 lines of its own
// JavaScript on every start. A syntax error in those files fails the build.
//
//   embed_js <out.cpp> <a.js> <b.js> ...

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

#include "quickjs.h"

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: embed_js <out.cpp> <file.js>...\n");
        return 2;
    }
    JSRuntime* rt = JS_NewRuntime();
    JSContext* ctx = JS_NewContext(rt);

    std::ostringstream out;
    out << "// Generated by tools/embed_js.cpp from src/js/*.js — do not edit.\n"
           "#include \"embedded_js.hpp\"\n\nnamespace rtn {\n\nnamespace {\n";
    std::ostringstream table;
    int failed = 0;
    for (int i = 2; i < argc; ++i) {
        std::string path = argv[i];
        std::ifstream in(path, std::ios::binary);
        std::stringstream ss;
        ss << in.rdbuf();
        std::string src = ss.str();
        std::string name = path.substr(path.find_last_of('/') + 1);
        std::string filename = "rtn:internal/" + name;

        JSValue fn = JS_Eval(ctx, src.c_str(), src.size(), filename.c_str(),
                             JS_EVAL_TYPE_GLOBAL | JS_EVAL_FLAG_STRICT | JS_EVAL_FLAG_COMPILE_ONLY);
        if (JS_IsException(fn)) {
            JSValue e = JS_GetException(ctx);
            const char* msg = JS_ToCString(ctx, e);
            JSValue stack = JS_GetPropertyStr(ctx, e, "stack");
            const char* where = JS_ToCString(ctx, stack);
            std::fprintf(stderr, "%s: %s\n%s", path.c_str(), msg ? msg : "error", where ? where : "");
            JS_FreeCString(ctx, where);
            JS_FreeCString(ctx, msg);
            JS_FreeValue(ctx, stack);
            JS_FreeValue(ctx, e);
            ++failed;
            continue;
        }
        size_t size = 0;
        uint8_t* bytes = JS_WriteObject(ctx, &size, fn, JS_WRITE_OBJ_BYTECODE);
        JS_FreeValue(ctx, fn);

        out << "const unsigned char kFile" << i << "[] = {";
        for (size_t b = 0; b < size; ++b) out << (b % 24 == 0 ? "\n    " : "") << static_cast<int>(bytes[b]) << ",";
        out << "\n};\n";
        table << "    {\"" << name << "\", kFile" << i << ", sizeof(kFile" << i << ")},\n";
        js_free(ctx, bytes);
    }
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    if (failed) return 1;

    out << "\n}  // namespace\n\nconst EmbeddedJs kEmbeddedJs[] = {\n" << table.str() << "};\n\n"
        << "const std::size_t kEmbeddedJsCount = sizeof(kEmbeddedJs) / sizeof(kEmbeddedJs[0]);\n\n}  // namespace rtn\n";
    std::ofstream file(argv[1], std::ios::binary);
    file << out.str();
    return file ? 0 : 1;
}
