#pragma once

#include <cstddef>

namespace rtn {

struct EmbeddedJs {
    const char* name;
    const char* source;
};

// Generated by cmake/embed_js.cmake from src/js/*.js
extern const EmbeddedJs kEmbeddedJs[];
extern const std::size_t kEmbeddedJsCount;

}  // namespace rtn
