#pragma once

#include <cstddef>

namespace rtn {

struct EmbeddedJs {
    const char* name;
    const unsigned char* bytecode;  // QuickJS bytecode of the file (a script)
    std::size_t size;
};

// Generated by tools/embed_js.cpp from src/js/*.js
extern const EmbeddedJs kEmbeddedJs[];
extern const std::size_t kEmbeddedJsCount;

}  // namespace rtn
